DATA:
  BANDS: 176
  BATCH_SIZE: 256
  DATASET: hsi
  DATA_PATH: ./dataset/HSI_data
  HSI_DATASET: KSC
  PATCH_SIZE: 7
  TRAIN_RATIO: 0.15
  VAL_RATIO: 0.1
MODEL:
  NAME: vHeat4HSI_KSC
  NUM_CLASSES: 13
  TYPE: vHeat4HSI
  VHEAT:
    DEPTHS:
    - 1
    - 2
    - 2
    - 1
    EMBED_DIM: 176
    MLP_RATIO: 2.0
OUTPUT: ./output_hsi/KSC
PRINT_FREQ: 10
SAVE_FREQ: 10
SEED: 42
TRAIN:
  BASE_LR: 0.001
  EPOCHS: 600
  WEIGHT_DECAY: 0.05
